name=input("enter your name here")
surname=input("enter your surname here")
age=input("enter your age here")
father_name=input("enter your father name here")
length=len(name)
print("Number of letters in your name:" + str(length) )
print("Your fullname is :" + name + " " + surname)
print("Your age is :" + age)
print("Your father name is :" + father_name)